version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  #Build the Java app
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-
      - run:
          name: Resolve deps (offline)
          command: mvn -B -q -DskipTests dependency:go-offline
      - run:
          name: Package (skip tests)
          command: mvn -B -q -DskipTests package
      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths: [ "~/.m2" ]
      - persist_to_workspace:
          root: .
          paths: [ "." ]
          
  #Test
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run getProductByIdTest
          command: >
            mvn -B -q
            -Dspring.profiles.active=test
            -Dtest='com.simple_inventory_tracker.project.controller.ProductControllerTest#getProductByIdTest'
            test
      - run:
          name: Run validProductCreationTest
          command: >
            mvn -B -q
            -Dspring.profiles.active=test
            -Dtest='com.simple_inventory_tracker.project.controller.ProductControllerTest#validProductCreationTest'
            test
      - run:
          name: Run invalidProductCreationTest
          command: >
            mvn -B -q
            -Dspring.profiles.active=test
            -Dtest='com.simple_inventory_tracker.project.controller.ProductControllerTest#invalidProductCreationTest'
            test



  #Containerize the Java app
  docker_build:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: willhooi/inventory-tracker
      IMAGE_TAG: << pipeline.git.revision >>
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: 
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$IMAGE_TAG .


workflows:
  ci_and_cd:
    jobs:
      # Build Java app on both develop and release
      - build:
          filters:
            branches:
              only:
                - develop
                - release

      # Run test after build on both branches
      - test:
          requires:
            - build 
          filters:
            branches:
              only:
                - develop
                - release

      # Docker build only on release & if tests passed
      - docker_build:
          requires:
            - test
          filters:
            branches:
              only: release
      
      # Docker deploy only on release & if docker_build successful

      # Run Synk vulnerability scan after build